name: book_app
description: "A Digital Book Library."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5
  responsive_sizer: ^3.3.1
  sqflite: ^2.3.3+1

dependency_overrides:
  analyzer: 7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  assets:
    - assets/
